# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 02:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), null=True, size=None)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('canonical', models.CharField(max_length=256)),
                ('discipline', models.CharField(max_length=256, null=True)),
                ('slug', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_name', models.CharField(max_length=256, null=True)),
                ('directory_name', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('department', models.CharField(max_length=256, null=True)),
                ('home_department', models.CharField(max_length=256, null=True)),
                ('uid', models.CharField(max_length=256, null=True)),
                ('success', models.BooleanField(default=False)),
                ('department_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.Department')),
            ],
            options={
                'ordering': ['person__last'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=256, null=True)),
                ('last', models.CharField(max_length=256, null=True)),
                ('slug', models.CharField(max_length=256, null=True)),
                ('search_attempt', models.BooleanField(default=False)),
                ('directory_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.DirectoryRecord')),
            ],
            options={
                'ordering': ['last'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=256, null=True)),
                ('first', models.CharField(max_length=256, null=True)),
                ('middle', models.CharField(max_length=256, null=True)),
                ('last', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('title_category', models.CharField(max_length=256, null=True)),
                ('title_qualifier', models.CharField(max_length=256, null=True)),
                ('title_year_code', models.CharField(max_length=16, null=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('regular', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('base', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('eff_date', models.CharField(max_length=16, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.Person')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
